after-login-command = []
after-startup-command = [
    'exec-and-forget /opt/homebrew/bin/borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000'
]
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'pgrep -fi swiftbar && open -g "swiftbar://refreshplugin?name=aerospace-workspaces"'
]

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 9
inner.vertical =   9
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]
# Disable annoying hide keybindings
cmd-h = []

ctrl-alt-shift-cmd-e = 'exec-and-forget /Users/jens/.local/bin/,open-or-focus-firefox'
ctrl-alt-shift-cmd-p = 'exec-and-forget open -a 1Password'
ctrl-alt-shift-cmd-a = 'exec-and-forget open -a Beeper && open -a Signal'
ctrl-alt-shift-cmd-c = 'exec-and-forget open -a "Calendar"'
ctrl-alt-shift-cmd-s = 'exec-and-forget open -a Slack'
ctrl-alt-shift-cmd-z = 'exec-and-forget pgrep -fi zoom.us && open -a zoom.us'
ctrl-alt-shift-cmd-o = 'exec-and-forget open -a Obsidian'
ctrl-alt-shift-cmd-t = 'exec-and-forget open -a "Microsoft Teams"'
ctrl-alt-shift-cmd-v = 'exec-and-forget open -a "Visual Studio Code"'
ctrl-alt-shift-cmd-enter = 'exec-and-forget open -a WezTerm'
cmd-esc = 'exec-and-forget open -a "Mission Control"'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
ctrl-shift-equal = 'balance-sizes'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'workspace-back-and-forth'
alt-backtick = 'workspace-back-and-forth'

alt-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
b = ['exec-and-forget /opt/homebrew/bin/borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000', 'mode main']
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'im.beeper'
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 10']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace 10']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']

[workspace-to-monitor-force-assignment]
10 = 'built-in'
