# Taps
tap "AdoptOpenJDK/openjdk" # java
tap "bufbuild/buf"
tap "buo/cask-upgrade" # cask upgrade tool, used by topgrade
tap "holgerbrandl/tap" # kscript
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers" # yubico
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jsfr/jsfr" # urlview
tap "koekeishiya/formulae" # yabai + skhd
tap "ms-jpq/sad" # sad
tap "nextdns/tap" # NextDNS
tap "srkomodo/tap" # shadowfox updater

# Brews
brew "atool"
brew "aws-iam-authenticator"
brew "awscli"
brew "bash"
brew "bat"
brew "buf"
brew "cocoapods"
brew "codemod"
brew "coreutils"
brew "dash"
brew "datamash"
brew "desk"
brew "direnv"
brew "docker-clean"
brew "elixir"
brew "exa"
brew "fd"
brew "fennel"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "go"
brew "gradle"
brew "grv"
brew "htop"
brew "httpie"
brew "hyperfine"
brew "iperf3"
brew "jq"
brew "jsfr/jsfr/urlview", args: ["HEAD"]
brew "just"
brew "kotlin"
brew "ktlint"
brew "kubectl"
brew "libqalculate"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "magic-wormhole"
brew "mas"
brew "mkcert"
brew "mkcert"
brew "mosh"
brew "n"
brew "neovim", args: ["HEAD"]
brew "nextdns"
brew "nss"
brew "oath-toolkit"
brew "pgcli"
brew "pipx"
brew "postgresql"
brew "protobuf"
brew "python"
brew "rargs"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "sad"
brew "shadowfox-updater"
brew "shellcheck"
brew "shfmt"
brew "skhd"
brew "starship"
brew "tealdeer"
brew "terraform"
brew "tmux"
brew "topgrade"
brew "vault"
brew "watch"
brew "yabai"
brew "zoxide"

# Casks
cask "1password"
cask "alacritty"
cask "aws-vault"
cask "bartender"
cask "discord"
cask "docker"
cask "firefox"
cask "font-jetbrains-mono"
cask "hammerspoon"
cask "insync"
cask "intellij-idea-ce"
cask "joplin"
cask "linear-linear"
cask "maccy"
cask "miro"
cask "mullvadvpn"
cask "notion"
cask "onyx"
cask "pocket-casts"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "steermouse"
cask "sublime-merge"
cask "swiftdefaultappsprefpane"
cask "tableplus"
cask "virtualbox"
cask "yubico-yubikey-manager"
cask "zoom"
