# Taps
tap "AdoptOpenJDK/openjdk" # java
tap "buo/cask-upgrade" # cask upgrade tool, used by topgrade
# tap "fabianishere/personal" # pam_reattach to allow use of pam_tid within tmux
tap "filippo.io/age", "https://filippo.io/age" # age
tap "holgerbrandl/tap" # kscript
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jsfr/jsfr" # urlview
tap "koekeishiya/formulae" # yabai + skhd
tap "ms-jpq/sad" # sad
tap "srkomodo/tap" # shadowfox updater

# Brews
# brew "codemod"
# brew "dep"
# brew "exa"
# brew "fabianishere/personal/pam_reattach"
# brew "fastmod"
# brew "fpp"
# brew "holgerbrandl/tap/kscript"
# brew "hyperfine"
# brew "jo"
# brew "mitmproxy"
# brew "sk"
brew "age"
brew "atool"
brew "aws-iam-authenticator"
brew "awscli"
brew "bash"
brew "bat"
brew "cocoapods"
brew "coreutils"
brew "datamash"
brew "deno"
brew "desk"
brew "direnv"
brew "docker-clean"
brew "elixir"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "glfw"
brew "go"
brew "gradle"
brew "grv"
brew "htop"
brew "httpie"
brew "iperf3"
brew "jq"
brew "jsfr/jsfr/urlview", args: ["HEAD"]
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "kotlin"
brew "ktlint"
brew "kubectl"
brew "libqalculate"
brew "magic-wormhole"
brew "mas"
brew "mkcert"
brew "ms-jpq/sad/sad"
brew "n"
brew "neovim"
brew "pgcli"
brew "postgresql"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "srkomodo/tap/shadowfox-updater"
brew "starship"
brew "terraform"
brew "tmux"
brew "topgrade"
brew "vault"
brew "watch"

# Casks
# cask "boxy-suite"
# cask "datagrip"
cask "1password"
cask "adoptopenjdk/openjdk/adoptopenjdk11"
cask "alacritty"
cask "aws-vault"
cask "bartender"
cask "dash"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "font-jetbrains-mono"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hammerspoon"
cask "hiddenbar"
cask "insomnia"
cask "intellij-idea-ce"
cask "maccy"
cask "mullvadvpn"
cask "ngrok"
cask "notion"
cask "onyx"
cask "pocket-casts"
cask "react-native-debugger"
cask "sensiblesidebuttons"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "tableplus"
cask "transmission"
cask "virtualbox"
cask "zoomus"
