# Taps
tap "AdoptOpenJDK/openjdk" # java
tap "buo/cask-upgrade" # cask upgrade tool
tap "fabianishere/personal" # pam_reattach to allow use of pam_tid within tmux
tap "filippo.io/age", "https://filippo.io/age" # age
tap "github/gh" # github cli (gh)
tap "holgerbrandl/tap" # kscript
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jsfr/jsfr" # urlview
tap "koekeishiya/formulae" # yabai + skhd
tap "srkomodo/tap" # shadowfox updater

# Brews
brew "age"
brew "atool"
brew "aws-iam-authenticator"
brew "awscli"
brew "bat"
brew "brew-gem"
brew "cocoapods"
brew "codemod"
brew "coreutils"
brew "datamash"
brew "dep"
brew "desk"
brew "diff-so-fancy"
brew "direnv"
brew "docker-clean"
brew "elixir"
brew "exa"
brew "fabianishere/personal/pam_reattach"
brew "fastmod"
brew "fd"
brew "fish"
brew "fpp"
brew "gem-neovim"
brew "gem-xcpretty"
brew "git"
brew "git-delta"
brew "git-extras"
brew "github/gh/gh"
brew "glfw"
brew "go"
brew "gradle"
brew "grv"
brew "holgerbrandl/tap/kscript"
brew "htop"
brew "httpie"
brew "hugo"
brew "jo"
brew "jq"
brew "jsfr/jsfr/urlview", args: ["HEAD"]
brew "kakoune"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "ktlint"
brew "libqalculate"
brew "mas"
brew "mitmproxy"
brew "mkcert"
brew "neovim"
brew "node@12"
brew "pass"
brew "pgcli"
brew "postgresql"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "sk"
brew "srkomodo/tap/shadowfox-updater"
brew "starship"
brew "terraform"
brew "tmux"
brew "topgrade"
brew "watch"
brew "hyperfine"
brew "fzf"

# Casks
cask "1password"
cask "adoptopenjdk/openjdk/adoptopenjdk11"
cask "alacritty"
cask "android-studio"
cask "aws-vault"
cask "boxy-suite"
cask "copyq"
cask "dash"
cask "datagrip"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "font-jetbrains-mono"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hammerspoon"
cask "hiddenbar"
cask "insomnia"
cask "intellij-idea-ce"
cask "karabiner-elements"
cask "mullvadvpn"
cask "ngrok"
cask "notion"
cask "obsidian"
cask "pocket-casts"
cask "rcdefaultapp"
cask "react-native-debugger"
cask "sensiblesidebuttons"
cask "shortcat"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "trailer"
cask "transmission"
cask "virtualbox"
cask "viscosity"
