#!/usr/bin/env sh

username="$1"
token="$2"

url="https://api.github.com/graphql"

/usr/bin/curl \
  $url \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: bearer $token" \
  --data '{"query": "query ActivePullRequests($query: String!) { search(query: $query, type: ISSUE, first: 100) { nodes { ... on PullRequest { author { login } url title isReadByViewer isDraft reviewDecision reviewRequests(first: 100) { nodes { requestedReviewer { ... on User { login } } } } assignees(first: 100) { nodes { login } } } } } }", "variables": { "query": "sort:updated-desc type:pr state:open involves:'$username'" } }'
