# yaml-language-server: $schema=https://raw.githubusercontent.com/mattn/efm-langserver/master/schema.json
version: 2
log-file: /Users/jens/debug.log
log-level: 1
root-markers:
  - .git/
lint-debounce: 1s

tools:
  eslint: &eslint
    prefix: "eslint"
    lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
  typos: &typos
    prefix: "typos"
    lint-command: 'typos --format brief -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  javascript:
    - <<: *eslint
  typescript:
    - <<: *eslint
  =:
    - <<: *typos
