#!/usr/bin/env sh

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          3              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  05             \
    bottom_padding               05             \
    left_padding                 05             \
    right_padding                05             \
    window_gap                   05             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# rules
yabai -m rule --add app="^Finder$" title="^(Copy)?$" layer=above manage=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Steam$" border=off layer=above manage=off
yabai -m rule --add app="^rmenu$" border=off layer=above manage=off sticky=on
yabai -m rule --add app="^Access$" border=off layer=above manage=off
yabai -m rule --add app="^SongsOfConquest$" border=off manage=off
yabai -m rule --add app="^GOG Galaxy.*$" border=off manage=off
yabai -m rule --add app="^Okta Verify.*$" manage=off layer=above

yabai -m rule --add app="^Signal$" space=^8
yabai -m rule --add app="^Mimestream$" space=^9
yabai -m rule --add app="^Slack$" space=^10

## add signals for hammerspoon yabai widget
hs -c "spoon.YabaiSpaces:add_signals()"

# go through all spaces to pick up all windows
active_space=$(yabai -m query --spaces --space | jq -r ".index")
last_space=$(yabai -m query --spaces | jq -r "[.[] | .index] | max")
for i in $(seq 1 "$last_space"); do yabai -m space --focus "$i"; sleep 0.1; done
yabai -m space --focus "$active_space"

echo "yabai configuration loaded.."
