#!/usr/bin/env sh

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  08             \
    bottom_padding               08             \
    left_padding                 08             \
    right_padding                08             \
    window_gap                   09             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# rules
yabai -m rule --add app='^Finder$' title='^(Copy)?$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^Steam$' manage=off
yabai -m rule --add app='^rmenu$' manage=off sticky=on
yabai -m rule --add app='^Access$' manage=off
yabai -m rule --add app='^SongsOfConquest$' manage=off
yabai -m rule --add app='^GOG Galaxy.*$' manage=off
yabai -m rule --add app='^Okta Verify.*$' manage=off

yabai -m rule --add app='^Signal$' space=^7
yabai -m rule --add app='^Beeper$' space=^7
yabai -m rule --add app='^Notion Calendar$' space=^8
yabai -m rule --add app='^Morgen$' space=^8
yabai -m rule --add app='^Calendar$' space=^8
yabai -m rule --add app='^Slack$' space=^9

# Kill the Music.app if it launches because it sucks
yabai -m signal --add label=kill_music_app event=application_launched app="^Music$" action="killall Music"

# Update swiftbar spaces plugin on changes
yabai -m signal --add label=swiftbar_1 event=application_launched       action="pgrep -fi swiftbar && open -g 'swiftbar://refreshplugin?name=yabai-spaces'"
yabai -m signal --add label=swiftbar_2 event=application_front_switched action="pgrep -fi swiftbar && open -g 'swiftbar://refreshplugin?name=yabai-spaces'"
yabai -m signal --add label=swiftbar_3 event=application_terminated     action="pgrep -fi swiftbar && open -g 'swiftbar://refreshplugin?name=yabai-spaces'"
yabai -m signal --add label=swiftbar_4 event=space_changed              action="pgrep -fi swiftbar && open -g 'swiftbar://refreshplugin?name=yabai-spaces'"

# go through all spaces to pick up all windows
_yabai_iterate_spaces() {
    active_space=$(yabai -m query --spaces --space | jq -r ".index")
    last_space=$(yabai -m query --spaces | jq -r "[.[] | .index] | max")
    for i in $(seq 1 "$last_space"); do yabai -m space --focus "$i"; sleep 0.1; done
    yabai -m space --focus "$active_space"
}
_yabai_iterate_spaces

# Add borders
borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000
